### ISSUE TITLE
401 Unauthorized: Temp URL invalid" when using CreateTemporaryPublicUri

### ISSUE THREAD

**Issue by mlb5000** [openstacknetsdk/openstack.net#432]
When loading the URL returned by CreateTemporaryPublicUri I always get an error that says "401 Unauthorized: Temp URL invalid".

Code is as follows:

```
        const string region = "DFW";

        //// connect to cloud
        var credentials = new CloudIdentity {APIKey = "myapikey", Username = "myusername"};
        var cloudFilesProvider = new CloudFilesProvider(credentials);

        //// get container
        var container = cloudFilesProvider.GetContainerHeader(ctr, region);

        //// get a file object
        var fileParts = file.Split('/');
        var tmp_filename = fileParts.Last();

        var metadata = cloudFilesProvider.GetAccountMetaData();
        var temp_url = cloudFilesProvider.CreateTemporaryPublicUri(HttpMethod.GET, ctr, tmp_filename, metadata[CloudFilesProvider.TempUrlKey],
            new DateTimeOffset(DateTime.Now.Ticks, new TimeSpan(0,0,0,120)), region, false, credentials);
```

What am I doing wrong here?

**Comment by matthewcarnaghi** [comment]
I realize this was 3 years ago and this may seem really dumb, but you're sure the object exists in that container? I was getting a 401 but it was because I needed to call cloudFilesProvider.CreateObject() first, and pass in a stream of the bytes so the object existed in that container first. Then, I created a temp url using the same filename I just created.
