### ISSUE TITLE
How do I use the SDK with the different .NET Framework versions. For example, 3.5 vs. 4.0 vs. 4.5?

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#483]
Are there different assemblies for each .NET Framework version?

What's the difference? What are the "gotchas" I need to watch for?

**Comment by sharwell** [comment]
Hi @DonSchenck,

This is a great question, especially considering it was one of the primary motivating factors for the transition towards a V2 SDK. It's going to take me a little bit to cover a common scenarios from different perspectives, but I want to make sure you have all the information you need. :smile:

**Comment by sharwell** [comment]
I'll start with an overview of what it means to support multiple versions of the .NET framework, along with abstract metrics one might use to measure success. I'm pretty :sleepy: this evening so I expect to continue with an explanation of specific SDK decisions tomorrow. :smile:

Since the OpenStack.NET SDK is a library (as opposed to an application), the considerations for multiple versions of .NET are special. The goals we want to meet are:

1. Allow as many .NET applications to use the SDK as is "reasonably possible".
1. Do not degrade the experience for users working with new versions of .NET for the sake of supporting older versions as well.
1. Allow additional libraries to sit between the SDK and the application without making the process overly complex.

### Support as many applications as "reasonably possible"

In general, application developers prefer to work with newer frameworks when possible. Over time, fewer and fewer applications rely on versions of the .NET framework we currently consider "older".

1. Support customer applications we *know* exist and run with specific versions of .NET. One common measure of this is "latest minus one", which would be .NET 4.0. Other metrics exist, but for the sake of the following discussion we'll assume .NET 4.0 support is a requirement.
1. Provided the first point is met, also support any other version of .NET which does not require extensive special work. Continuing the example, suppose the library works with the Task Parallel Library. In this case, a build of the Task Parallel Library is available for .NET 3.5 which provides a nearly identical API to the .NET 4.0 release. For very little extra work, .NET 3.5 can be supported. Even if .NET 3.5 support is not a hard requirement for the library, the library developers might choose to support it since it is convenient.

### Do not degrade the experience for users working with newer .NET releases

When developing a library for multiple versions of .NET, situations will arise where a type or method is available is some supported versions of .NET, but not in others. If users working with frameworks that support these elements *expect* them to be supported, then it's important to not let the support for older versions of .NET prevent the library from supporting these types. In this library, a common case that arose is the `IProgress<T>` enumeration, which is only available in .NET 4.5 and newer.

Resolving these cases always requires the library ship multiple binaries which share code where possible, but handle these special cases in the manner most suited to a specific target framework. For missing members, resolving the difference between builds generally only requires the definition of an `internal` helper method, where the method is implemented uniquely for each framework. There are two primary strategies for maximizing compatibility of types when working with multiple builds.

#### Type substitution

Assume a library **MyLibrary** targets .NET 4.0 and newer, and wants to use the `IProgress<T>` interface .NET 4.5. The library authors create two assemblies: **MyLibrary.dll** targeting .NET 4.0 and **MyLibrary.dll** targeting .NET 4.5.

In the .NET 4.0 build, the library includes a definition for `System.IProgress<T>` which is an exact match for the interface provided in .NET 4.5. When building for .NET 4.0, the rest of the library code which references `IProgress<T>` will resolve to this library-provided interface type.

In the .NET 4.5 build, the definition of `IProgress<T>` is omitted and the library code directly references the .NET 4.5 `IProgress<T>` directly.

When a library provides a `public` definition for a standard type in one assembly but not in another, it is very important to use the `[TypeForwardedTo]` attribute to ensure the libraries are compatible with each other. More information about this will be included in a later comment. For example:

* The `Tuple` class, [defined by OpenStack.NET](https://github.com/openstacknetsdk/openstack.net/blob/bb0e8dfa42bd1ab32c233ee917592ec72673e350/src/OpenStack.Net/System/Tuple.cs#L34) for certain builds, is public, so it requires the remaining builds include a `[TypeForwardedTo]` attribute pointing to the new location where the class is defined.
* The `NonSerializedAttribute`, [defined by OpenStack.NET](https://github.com/openstacknetsdk/openstack.net/blob/master/src/OpenStack.Net/System/NonSerializedAttribute.cs) for certain builds, does not need to include a `[TypeForwardedTo]` attribute because `NonSerializedAttribute` is declared `internal`.

#### Interchangeable types

Interchangeable types are unique types which are defined in a library for all framework targets, but are interchangable with framework-provided types in applications which target a framework version which includes those types. The OpenStack.NET SDK recently included pull request #471, which uses this strategy for the `AddressFamily` and `IPAddress` types.

The OpenStack.NET SDK (V2) now includes its own `AddressFamily` structure, which is used by all SDK APIs that would normally use [`System.Net.Sockets.AddressFamily`](https://msdn.microsoft.com/en-us/library/system.net.sockets.addressfamily.aspx) if it were restricted to .NET 4.0. Unfortunately this enumeration is not available in some supported target frameworks. For the builds that *do* support this enumeration, an implicit operator to and from the original type is provided, so users can pass `System.Net.Sockets.AddressFamily.InterNetwork` to any SDK API that would normally expect `OpenStack.Net.AddressFamily.Ipv4` to be sent. Likewise, Windows Store Apps can pass `Windows.Networking.HostNameType.Ipv4` to any of these SDK API methods.

**Comment by sharwell** [comment]
Now I'd like to go into further detail on the specific manner in which the .NET SDK approaches each of these topics.

### Supporting applications

The .NET SDK started with the "current version minus one" approach for the support requirement. At the time this decision was made for the V1 SDK, many .NET customers using OpenStack hosting providers were known to use .NET 3.5. For the V2 SDK, a majority of users had switched to .NET 4.0 and higher, so the hard support requirement was placed there. However, the practices put into place for the V1 SDK prepared us well for continuing the practice of supporting .NET 3.5 customers, so we chose to do so.

The primary difference with the V2 SDK in this area is the added support for three "Portable Class Library" (PCL) targets, which offers broad support for Windows Phone 8, Windows Phone Apps 8.1, Silverlight 5, and Windows 8 Store Apps. We have a further goal of supporting Mono as well as Xamarin applications for Android and iOS (and the PCL targets should already support this), although these targets are not currently tested. The added support for so many new targets posed a few new challenges for developers, but reliable solutions for the issues we identified are already in place.

| Framework | Profile | SDK | Notes |
| .NET 3.5 | Full | V1, V2 | |
| .NET 4.0 | Full | V1, V2 | |
| .NET 4.5 | n/a | V1, V2 | The V1 SDK automatically includes a required "compatibility layer" assembly in this use case |
| Portable Class Library (Legacy) | Profile 328 and any subset | V2 | Not reasonably possible with V1 |
| Portable Class Library | Profile 259 | V2 | Not reasonably possible with V1 |
| .NET for Windows Store | Windows 8+ | V2 | Not reasonably possible with V1 |

### Proper support for each target

The .NET SDK uses both type substitution and interchangeable types to provide clean support across a variety of frameworks.

#### Type substitution

In general, type substitution is implemented by providing compatibility libraries alongside the SDK which support older versions of the .NET Framework. For example, the V2 SDK is able to use the `HttpClient` library by in the following way:

| Target | `HttpClient` library |
| --- | --- |
| .NET 3.5 | [Rackspace.HttpClient35](https://www.nuget.org/packages/Rackspace.HttpClient35/) |
| .NET 4.0 | [Microsoft.Net.Http](https://www.nuget.org/packages/Microsoft.Net.Http/) |
| .NET 4.5 | Included in framework |
| .NET Portable Class Library (Legacy) | [Microsoft.Net.Http](https://www.nuget.org/packages/Microsoft.Net.Http/) |
| .NET Portable Class Library | Included in framework |
| .NET for Windows Store Apps | Included in framework |

The Rackspace.HttpClient35 library can be upgraded to the Microsoft.Net.Http library without recompiling code¹. Likewise, the Microsoft.Net.Http library can be upgraded to the .NET Framework-provided library without recompiling code.

¹ While writing this comment I discovered rackerlabs/dotnet-httpclient35#7 and rackerlabs/dotnet-httpclient35#8, but once these issues are resolved the statement will be true.

#### Interchangeable types

The concept of interchangeable types was first introduced to the V2 SDK in #468. For months before this I had serious concerns about the use of type substitution to meet the needs of types like `AddressFamily` and `IPAddress`. These types have two particular characteristics which alone cause problems for type substitution and together make it generally unworkable.

1. These types are not contained within a simple assembly which is either provided or omitted in a particular framework. By contrast, the `HttpClient` type is part of the **System.Net.Http** library which is missing altogether from .NET 3.5 and .NET 4.0. The entire `System.Collections.Immutable` namespace is not included in any version of .NET, and the official implementation only supports .NET 4.5+. `IPAddress`, on the other hand, is part of the **System** assembly. If we use type substitution for `IPAddress`, there is a high likelihood of conflicting with another library that *also* defines `IPAddress`, and the result is user code starts to look like the following (if this doesn't make sense, then it should be especially obvious why we want to **avoid** it).

    ```csharp
    #if PORTABLE_CLASS_LIBRARY
      extern alias openstacknet;
      extern alias otherlibrary;
      using OpenStackIPAddress = openstacknet::System.Net.IPAddress;
      using OtherLibraryIPAddress = otherlibrary::System.Net.IPAddress;
    #else
      using OpenStackIPAddress = System.Net.IPAddress;
      using OtherLibraryIPAddress = System.Net.IPAddress;
    #endif
    ```

2. These types have different representations in different libraries. For example, the [`AddressFamily`](https://msdn.microsoft.com/en-us/library/system.net.sockets.addressfamily.aspx) enumeration from .NET 3.5, 4.0, and 4.5 is missing from the Portable Class Libraries, but .NET for Windows Store Apps (a specific flavor of the PCL) provides a *different* type [`HostNameType`](https://msdn.microsoft.com/library/windows/apps/windows.networking.hostnametype.aspx) enumeration which serves the same purpose. The `AddressFamily` enumeration and `HostNameType` enumeration do not use the same values to represent IP v4 and IP v6, so it's not even possible to support both by treating the enumeration as an integer and casting between them.

### Additional libraries

In the original designs for the SDK, the primary focus was providing a library which is directly consumed by a final application. Over time, it became clear that another valuable scenario is a 3<sup>rd</sup> party library consumes the SDK, and the final application consumes *both* the SDK and this 3<sup>rd</sup> party library. In this situation, it is undesirable to *force* the 3<sup>rd</sup> party library to ship 6 separate builds of the library (because we ship 6 builds of the V2 SDK). A clean strategy for dealing with this was originally implemented in another project which ships **9** separate builds (seriously: tunnelvisionlabs/antlr4cs#87).

The OpenStack.NET SDK (V2) is *intended* to support a policy almost identical to the one described in the [Assembly Strong Name Policy](https://github.com/tunnelvisionlabs/antlr4cs#assembly-strong-name-policy) section of the ANTLR 4 C# target readme file. Eventually that information will need to be communicated in proper terms here. However, this support requires each dependency of the OpenStack.NET to *also* support this policy. The following table lists libraries which the OpenStack.NET SDK depends on, along with the version of that library which does (or will) support this compatibility and any open issue(s) that need to be address prior to releasing this version.

| Dependency | Version | Issues |
| --- | --- | --- |
| Rackspace.Threading | 2.0.0 | rackerlabs/dotnet-threading#79 |
| Rackspace.UriTemplate | 1.0.0 | none |
| Rackspace.HttpClient35 | 1.0.0 | rackerlabs/dotnet-httpclient35#7, rackerlabs/dotnet-httpclient35#8 |
| Rackspace.Collections.Immutable | 1.1.x | Waiting for final release of [System.Collections.Immutable 1.1.x](https://www.nuget.org/packages/System.Collections.Immutable/1.1.33-beta) |
| TaskParallelLibrary | Unknown | Unknown² |
| Microsoft.* (multiple libraries) | Already supported | |
| Json.NET | | |

² This may prevent in-place upgrades from the .NET 3.5 release to a .NET 4.0+ release, but the work required to rewrite this library simply to add this feature is not "reasonably possible" as defined above.

**Comment by sharwell** [comment]
@DonSchenck I did my best to explain this in enough detail that other developers can continue to provide support for the wide range of target frameworks supported by this library. Documentation for users will certainly be a small subset of this which is reworded in terms of what to do in specific user scenarios.

Please let me know if any part of this does not make sense.
