### ISSUE TITLE
What is the status of SDK v1?

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#485]
What is the status of SDK v1.x.x ?? 

Is work halted on this? Is it being superseded by v2.x.x?

**Comment by sharwell** [comment]
It's been a while since work on new features was done for the V1 SDK. As described in #483, the V1 SDK only supports a subset of current .NET users, so adding features to it may not be the best use of time. However, the latest v1.3 release includes several features which are marked preliminary. It would be a good idea to review these, and create a 1.4 release where the `<preliminary/>` marker is removed.

Despite its drawbacks (limited use in portable applications, and a code layout that doesn't distinguish between OpenStack functionality and Rackspace functionality), the current code base has proven quite stable for users, and provides access to a very wide range of products. I do not expect it to be officially deprecated for quite some time, although I also do not believe it will take much effort to maintain its current feature set.

**Comment by carolynvs** [comment]
I will be contributing to v1, i.e. the current release in production.
