### ISSUE TITLE
What is the status of SDK v2?

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#486]
Is v2.x.x. ready for use?
What remains to be done before it can be considered "Ready for general use"?

**Comment by sharwell** [comment]
As of 65a9005ebba0b3859ada97e4586d078df50f1434, the V2 SDK consists of a powerful framework for creating clients for HTTP APIs along with an extensible authentication API that supports OpenStack and Rackspace. Pull requests have been opened for individual features at different stages of completion. The closest is #448 to support the Object Storage Service (it's quite complete and likely ready for a final code review to see if it's ready to merge).

Due to a dependency on [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable/), it's unlikely that a "stable" 2.0.0 release would appear before the stable 1.1 release of this library in the spring. However, an initial preview could be ready for release as early as when Object Storage support is added.

"Ready for general use" depends on the number of features you require prior to saying 2.0.0 is ready. Reaching feature parity with V1 will take longer, since it supports somewhere between 11 and 13 services. However, the library was always intended to progressively replace the features from the V1 SDK, starting with the services that do not have asynchronous providers in V1 along with new OpenStack services which are not supported at all by V1 (Orchestration, Content Delivery, Networking).

**Comment by carolynvs** [comment]
I will be contributing to v1, i.e. the current release in production. All work to date on v2 is available in the v2 branch.
