### ISSUE TITLE
What is the status of Rackspace CDN Support?

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#487]
What is the status of and plan for Rackspace CDN Support?

Should it be added to SDK v1.x.x?

Should it be added to SDK v2.x.x?

**Comment by sharwell** [comment]
Pull request #475 is the ongoing development branch to add support to the V2 SDK. Since the V2 SDK supports a strict superset of the applications that the V1 SDK supports (and the SDKs can be used side-by-side), it is unlikely that we'll need to independently develop support in the V1 SDK.

**Comment by sharwell** [comment]
I added a number of comments to #475 covering issues that are currently blocking the merge. If someone wants to help resolve some of these, simply leave a note in that pull request (so we don't duplicate the work), and send a pull request to `sharwell/v2-content-delivery` (a branch in my fork) instead of the normal case of sending a pull request to `openstacknetsdk/master`.
