### ISSUE TITLE
How to get the CDN Service "Before" JSON Document?

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#491]
When executing the method ContentDeliveryClient.PrepareUpdateServiceAsync, what method is best for retrieving the "before" JSON doc?

This question assumes that the ServiceData parameter passed INTO the PrepareUpdateServiceAsync method is the "AFTER" (or desired) JSON document, and that the JSON Patch document (or 'diff') will be calculated within the PrepareUpdateServiceAsync method -- that is, the method will accept the new document, _retrieve_ the existing document, calculate the delta and call the JSON Patch method using the delta.

**Comment by DonSchenck** [comment]
The code -- need to get currentServiceData:


            // At this point, the serviceData parameter contains the NEW (AFTER) version
            // of the service data. Now, we need to retrieve the current (BEFORE) version,
            // then use those to calculate the difference, i.e. the JSON Patch document.


            string before_string = JsonConvert.SerializeObject(currentServiceData);
            string after_string = JsonConvert.SerializeObject(serviceData);

            var left = JToken.Parse(before_string);
            var right = JToken.Parse(after_string);
            var patchDoc = new JsonDiffPatch.JsonDiffer().Diff(left, right);

**Comment by sharwell** [comment]
The current architecture is intended to have the `Prepare*Async` calls follow as closely as possible to the format sent over the wire. In other words, the input to `PrepareUpdateServiceAsync` would be the patch representation.

The extension methods associated with a service provide a mechanism to simplify the most common use cases. For this call, the extension method would be `UpdateServiceAsync`. Since these are not simply `Prepare` calls, it's acceptable (though obviously not required) for the implementation of `UpdateServiceAsync` to make additional calls associated with this use case.

One thing to consider is we might not need the "before" document. If you simply treat the `left` variable as an empty JSON object in the code sample, the result might automatically match what the users are familiar with from other services.
