### ISSUE TITLE
Could not load type 'Newtonsoft.Json.JsonExtensionDataAttribute' from assembly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

### ISSUE THREAD

**Issue by cliffordru** [openstacknetsdk/openstack.net#493]
Hi, I am getting the following runtime exception:
Could not load type 'Newtonsoft.Json.JsonExtensionDataAttribute' from assembly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

This occurs when the following code runs:
_cloudFilesProvider.GetObject(containerName, mediaName, memStream);

I used NuGet and that referenced packages\Newtonsoft.Json.5.0.8\lib\net45\Newtonsoft.Json.dll but that assembly does not contain the JsonExtensionDataAttribute type.  When I try to reference a newer version of Newtonsoft that does have JsonExtensionDataAttribute, I get a runtime error:
Could not load file or assembly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

Can you assist with determining the proper version to use of Newtonsoft and/or openstack.net (currently referencing \packages\openstack.net.1.3.4.0\lib\net40\openstacknet.dll)?

Thanks

**Comment by sharwell** [comment]
It sounds like you may have another version of Json.NET on your system which is getting loaded instead of this one.

![image](https://cloud.githubusercontent.com/assets/1408396/7289414/5d365ada-e935-11e4-97e3-ebea57479cdf.png)

Here are the first steps I use to identify the problem:

1. Launch the application in the debugger, and set a breakpoint on the line that fails.
2. Open the **Debug &rarr; Windows &rarr; Modules** window.
3. Sort the modules list by the **Name** column.
4. Look at the **Path** column for each assembly named **Newtonsoft.Json.dll**. One of these will not be the assembly at the path you mentioned above.¹

¹ This is actually not necessarily correct. If you don't see the problematic assembly using the instructions above, you may need to set a breakpoint on the `TypeLoadException` and look at the modules window at the specific point of failure.

**Comment by cliffordru** [comment]
Thank you, you are correct, there was an older version of the dll hanging around.  Sorry for the false alarm.

**Comment by sharwell** [comment]
No problem, happy to help. :smile: 

Thank you again for taking the time to report the issues you faced.
