### ISSUE TITLE
Stop overriding NewtonSoft.Json GLOBAL defaults

### ISSUE THREAD

**Issue by depotjoe** [openstacknetsdk/openstack.net#551]
While I understand that there is a way for consumers of OpenStack.NET to override the DefaultSettings overrides by calling OpenStackNet.Configure(...), it is not something that is not intuitive.  Breaking an isolation barrier by modifying global settings is generally frowned upon and can be tricky to debug.

Many projects employ the NewtonSoft.Json library and the likelihood that one of OpenStack.NET's consumers might be using it is very high.  Isolation being a foundational precept for modular software, it would seem that the OpenStack.NET library should take the high road, in the context of global settings, and use local settings updates rather than overriding the global settings.

I would make a pull request, but this seems to be something that multiple contributors may want to weigh in on.

**Comment by carolynvs** [comment]
Thank you for bringing this up. I had made that change to alter the global settings because that's what our dependency [Flurl](https://github.com/tmenier/Flurl) uses (see [Flurl.Http.JsonHelper](https://github.com/tmenier/Flurl/blob/master/Flurl.Http.Shared/Util/JsonHelper.cs)).

I agree that changing the global settings like that is not desirable and will work with Flurl so that we can set the serialization settings just for our requests and not globally.

**Comment by carolynvs** [comment]
I've submitted an issue to Flurl with a possible solution. https://github.com/tmenier/Flurl/issues/49

**Comment by depotjoe** [comment]
Thanks!

**Comment by carolynvs** [comment]
Flurl 0.7 gives us full control over serialization and whatnot without having to touch global settings. Moving this issue to the next milestone.

**Comment by carolynvs** [comment]
Fixed by #582.

**Comment by carolynvs** [comment]
@depotjoe Apologies for this taking as long as it did! I was pulled away from working on the SDK for a while but I'm back now. :smile: 

If you would like to try this out before it's released, use [openstack.net 1.6.0-beta.2 from Nuget](https://www.nuget.org/packages/openstack.net/1.6.0-beta0002). As always, any and all feedback is greatly appreciated.
