### ISSUE TITLE
Latest Flurl dependency has a breaking change

### ISSUE THREAD

**Issue by Amethi** [openstacknetsdk/openstack.net#566]
Performing a Nuget update brings in Flurl.Http.Signed version 0.7.0 which seems to have a breaking change and is causing the following exception to be thrown in OpenStackNet.cs Line 49: `ConfigureFlurl(configureFlurl);` when instantiating an instance of `OpenStackIdentityProvider`

```
System.TypeLoadException occurred
  HResult=-2146233054
  Message=Could not load type 'Flurl.Http.Configuration.FlurlHttpConfigurationOptions' from assembly 'Flurl.Http, Version=0.7.0.0, Culture=neutral, PublicKeyToken=1308302a96879dfb'.
  Source=openstacknet
  TypeName=Flurl.Http.Configuration.FlurlHttpConfigurationOptions
  InnerException: 
```

**Comment by carolynvs** [comment]
Yup! I worked with Flurl to request those changes. Here is bug that drove everything. It is on the roadmap for the next release (coming in January). 

https://github.com/openstacknetsdk/openstack.net/issues/551

**Comment by carolynvs** [comment]
Closing as this is already being tracked under #551. It should be fixed in the [1.5.1 milestone](https://github.com/openstacknetsdk/openstack.net/milestones/v1.5.1).

**Comment by carolynvs** [comment]
Reopening as the real problem is that we need to update our NuGet spec file and set a highest version for each dependency.

**Comment by carolynvs** [comment]
Thank you bringing up this bad behavior! :smile: 

I've released a new version of the SDK, [1.5.0.2](https://www.nuget.org/packages/openstack.net/1.5.0.2), which pins our NuGet dependencies. That way when you install/upgrade, it doesn't jump to a version that isn't supported.

**Comment by Amethi** [comment]
Okay this is weird. I can see updates for SDK dependencies with Nuget. If I create a brand new console app and install the latest 1.5.0.2 SDK I can see updates for the dependencies we don't want to update:

https://imgur.com/a/nz3d3

Photo 1 - Installing SDK
Photo 2 - Installed packages
Photo 3 - Nuget Update window

It would seem the < operator in the nuget config file for the dependency versions isn't being honoured?

**Comment by carolynvs** [comment]
I'll make a new project and reproduce. Are you using VS 2015 or VS 2015 Update 1?

**Comment by Amethi** [comment]
Update 1.

Is there an ability to use an == operator in the nuget spec instead of a range? 

Sorry!

**Comment by carolynvs** [comment]
No need to apologize. I really appreciate the help.

Yes, we can pin it down to an exact version only. Before I do that, I want to make sure I can reproduce what you are seeing so that I'm sure that the fix ... fixes this silliness. :smile:

**Comment by carolynvs** [comment]
Okay, I see the same thing as you now!

When I try to upgrade Flurl.Http.Signed to the latest version (by clicking the update button), it does nothing. In the Output window I see the following. This isn't perfect (ideally NuGet wouldn't prompt you to update stuff that you can't) but at least it doesn't perform the update.

```
Attempting to gather dependencies information for package 'Flurl.Http.Signed.0.7.0' with respect to project 'NuGetDepsVerify', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Flurl.Http.Signed.0.7.0' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Flurl.Http.Signed 0.7.0' is not compatible with 'openstack.net 1.5.0.2 constraint: Flurl.Http.Signed (≥ 0.6.2.2015062601 && < 0.7.0)'.
```
Unfortunately, if I select all packages and try to batch update, something scary happens. NuGet decides to **downgrade** openstack.net to 1.5.0.1, so that it can update all the dependencies to the latest, even though I didn't ask it to touch that package...

![bad-nuget](https://cloud.githubusercontent.com/assets/1368985/12180806/4b2edd68-b544-11e5-95d0-49d1c09d25bc.png)

Even if I set all of openstack.net's dependencies to exact versions, that wouldn't stop NuGet from doing this. I will report it to the NuGet team and see what they say. But in the meantime, there isn't much I can do about it from my end. :disappointed:

**Comment by carolynvs** [comment]
I've submitted the bug to the NuGet team. https://github.com/NuGet/NuGetGallery/issues/2851

**Comment by Amethi** [comment]
:+1: Yeah I saw the downgrade too but didn't mention it as there was enough crazy already! Nice one on the bug raise.

**Comment by carolynvs** [comment]
FYI, they closed and copied the bug to a new location. https://github.com/NuGet/Home/issues/1903
